CC = g++
CFLAGS = -Wall -Wextra -std=c++11

all: ej3_bactracking ej4_1 ej5_bound

ej3_bactracking: ej3_bactracking.cpp
	$(CC) $(CFLAGS) -o ej3_bactracking ej3_bactracking.cpp

ej4_1: ej4_1.cpp
	$(CC) $(CFLAGS) -o ej4_1 ej4_1.cpp

ej5_bound: ej5_bound.cpp
	$(CC) $(CFLAGS) -o ej5_bound ej5_bound.cpp

clean:
	rm -f ej3_bactracking ej4_1 ej5_bound

