CC = g++
CFLAGS = -Wall -Wextra -std=c++11

all: ej3 ej4_p5_algoritmica

ej3: ej3.cpp
	$(CC) $(CFLAGS) -o ej3 ej3.cpp

ej4_p5_algoritmica: ej4_p5_algoritmica.cpp
	$(CC) $(CFLAGS) -o ej4_p5_algoritmica ej4_p5_algoritmica.cpp

ej5_bound: ej5_bound.cpp
	$(CC) $(CFLAGS) -o ej5_bound ej5_bound.cpp

clean:
	rm -f ej3 ej4_p5_algoritmica

