CC = g++
CFLAGS = -Wall -Wextra -std=c++11

all: aviones ej3 ej4_p5_algoritmica

ej3: ej3.cpp
	$(CC) $(CFLAGS) -o ej3 ej3.cpp

ej4_p5_algoritmica: ej4_p5_algoritmica.cpp
	$(CC) $(CFLAGS) -o ej4_p5_algoritmica ej4_p5_algoritmica.cpp

aviones: aviones.cpp
	$(CC) $(CFLAGS) -o aviones aviones.cpp

clean:
	rm -f aviones ej3 ej4_p5_algoritmica

